# Evaluate the results of the simulations
#########################################

# Input:  object as generated by the function do.sim().

# Output: bias and coverage of the prediction interval.

# d[2] represents the effect d_AB
# d[3] represents the effect d_AC; this is the one we are interested in.
# dd represents the effect d_CB

eval.sim <- function(sim.study, d_true = 0, k = 4) {
  n.sim <- length(sim.study$res[[1]])
  bias.fixed.normal <- bias.random.normal <- numeric(n.sim)
  coverage.fixed.normal <- coverage.random.normal <- numeric(n.sim)
  for (i in 1:n.sim) {
    
    # Bias:
    bias.fixed.normal[i] <- sim.study$res[[1]][[i]]$summary.fit[[1]]["d[3]", "Mean"] - d_true
    bias.random.normal[i] <- sim.study$res[[2]][[i]]$summary.fit[[1]]["d[3]", "Mean"] - d_true

    # Coverage:
    ci.low <- sim.study$res[[1]][[i]]$summary.fit[[2]]["d[3]", "2.5%"]
    ci.up <- sim.study$res[[1]][[i]]$summary.fit[[2]]["d[3]", "97.5%"]
    coverage.fixed.normal[i] <- (ci.low <= d_true) & (ci.up >= d_true)
    
    ci.low <- sim.study$res[[2]][[i]]$summary.fit[[2]]["d[3]", "2.5%"]
    ci.up <- sim.study$res[[2]][[i]]$summary.fit[[2]]["d[3]", "97.5%"]
    coverage.random.normal[i] <- ((ci.low <= d_true) & (ci.up >= d_true))
  }
  bias.fixed.normal <- mean(bias.fixed.normal)
  bias.random.normal <- mean(bias.random.normal)
  
  coverage.fixed.normal <- mean(coverage.fixed.normal)
  coverage.random.normal <- mean(coverage.random.normal)
  
  res <- data.frame("fixed.normal" = c(bias.fixed.normal, coverage.fixed.normal, NA),
                    "random.normal" = c(bias.random.normal, coverage.random.normal, NA),
                    "t.test" = NA,
                    "mixed.model" = NA)
  res[3, ] <- as.vector(as.numeric(sim.study$p_res[2, ]))
  row.names(res) <- c("Mean bias", "Coverage", "Type I error rate")
  print(format.r(res, k))
  knitr::kable(format.r(res, k), format = "latex", linesep = "")
}


# Functions to round numbers:
f.r <- function(x, k) format(round(x, k), nsmall = k, scientific = F)
format.r <- function(x, k = 3, cl.z = F) {
  val <- f.r(x, k)
  if (cl.z) {
    val[which(val == f.r(0, k))] <- paste("<", 0.1^k, sep = "")
  }
  val
}
